### ISSUE TITLE
Addon doesn't work with latest CDK

### ISSUE THREAD

**Issue by grdryn** [aerogear/minishift-mobilecore-addon#7]
The [Container Development Kit](https://developers.redhat.com/products/cdk/overview/) is a minishift distribution that provides OCP on RHEL. The current CDK (3.3.0) is based on minishift 1.11.0, which seems to match what the README here says.

```
$ minishift version
minishift v1.11.0+d7f374a
CDK v3.3.0-1
```

When running the `minishift start`, I see the following error:

```
-- Applying addon 'mobilecore':.Error during post cluster up configuration: Error executing command 'ssh command error:
command : tce-load -wi bash.tcz
err     : exit status 127
output  : bash: tce-load: command not found
':
```

This also makes me wonder: if this is an EL7 issue, does the plugin work with the CentOS image or Minikube image as described [here in the minishift docs](https://docs.openshift.org/latest/minishift/using/basic-usage.html#choosing-iso-image), or is it just the Boot2Docker one?

**Comment by secondsun** [comment]
Fixed here by removing tce I think https://github.com/aerogear/minishift-mobilecore-addon/commit/044c017daa0ce77d274390e7ca7b909468453982
