### ISSUE TITLE
installer error

### ISSUE THREAD

**Issue by pwright** [aerogear/minishift-mobilecore-addon#8]
getting following error:

output  : /home/docker/mobile-core/installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh: line 11: 8: [ERROR]You must provide namespace where service broker will run.

I think the add-on needs to be updated based on changes at:
https://github.com/aerogear/mobile-core/commit/409518d5f60868ff226492ac97ac33d03a01d4d9#diff-afadadc1877261687c4fde1e53d48b32

**Comment by philbrookes** [comment]
Hey Paul,

This is already updated, I wonder if you need to pull down the latest master of this repo and rerun:
```
minishift install -f /path/to/addon
```
